version: "3.8"

services:
  api:
    build: .
    container_name: judge0_api
    ports:
      - "2358:2358"
    depends_on:
      - db
      - redis
    env_file: .env.production
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      REDIS_URL: redis://:${REDIS_PASSWORD}@redis:6379
    restart: always
    command: ["sh", "./run"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:2358"]
      interval: 30s
      timeout: 10s
      retries: 5

  db:
    image: postgres:16
    container_name: judge0_db
    environment:
      POSTGRES_USER: judge0
      POSTGRES_PASSWORD: Skills@12345
      POSTGRES_DB: judge0
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:7
    container_name: judge0_redis
    command: [
      "bash", "-c",
      "docker-entrypoint.sh --appendonly no --requirepass \"$${REDIS_PASSWORD}\""
    ]
    environment:
      REDIS_PASSWORD: Skills@1234
    restart: always

volumes:
  pgdata:
