x-logging:
  &default-logging
  logging:
    driver: json-file
    options:
      max-size: 100M

services:
  server:
    image: judge0/judge0:latest
    volumes:
      - ./judge0.conf:/judge0.conf:ro
    ports:
      - "2358:2358"
    privileged: true
    env_file: .env
    environment:
      COUNT: 2
    <<: *default-logging
    restart: always

  worker:
    image: judge0/judge0:latest
    command: ["./scripts/workers"]
    volumes:
      - ./judge0.conf:/judge0.conf:ro
    privileged: true
    env_file: .env
    environment:
      COUNT: 2
    <<: *default-logging
    restart: always

  db:
    image: postgres:16.2
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - data:/var/lib/postgresql/data/
    <<: *default-logging
    restart: always

  redis:
    image: redis:7.2.4
    command: [
      "bash", "-c",
      "docker-entrypoint.sh --appendonly no --requirepass \"$${REDIS_PASSWORD}\""
    ]
    env_file: .env
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    <<: *default-logging
    restart: always

volumes:
  data:
